[package]
name = "example-basic"
description = "Example of how to use errore"
edition.workspace = true
license.workspace = true
publish = false
version.workspace = true

[dependencies]
env_logger = { version = "0.11.5" }
errore = { path = "../.." }
